# Generated by Django 2.0.5 on 2018-12-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
    ]
