# Generated by Django 2.0.5 on 2018-12-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_register', '0003_auto_20181207_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image/default.png', upload_to='image/')),
            ],
        ),
    ]
